### ISSUE TITLE
undefined method `fields` for nil

### ISSUE THREAD

**Issue by cout** [tra/spawnling#35]
I know it's bad etiquette to submit a bug report without a test case, but I'm not sure how to reproduce this in a small test case.  In my app, using spawnling from inside a controller action occasionally causes these exceptions to be thrown spuriously:

NoMethodError: undefined method `fields' for nil:NilClass

This is happening on a call to model.reload.

I suspect there may be some file descriptor left open in the child process that may need to be closed.

**Comment by mnoack** [comment]
Closing as this issue is stale. I'm happily accept pull requests to fix if this problem has been solved since your message (e.g. fixed in a fork)

Thank You
