### ISSUE TITLE
Rails 4 Passenger 4

### ISSUE THREAD

**Issue by timuckun** [tra/spawnling#39]
Is this gem ready for rails 4 and passenger 4?

**Comment by justin808** [comment]
Is there any issue with Passenger and Rails 4?

**Comment by mnoack** [comment]
I honestly don't know. Our project has stopped using spawnling (we were about to upgrade to rails 4 with spawnling so would have ensured it was supported), so I'm ready to add someone who actively uses it to maintain this project.

**Comment by mnoack** [comment]
Closing as this issue is stale. I note the code does pass in the rails 4 branch, but that the tests (at least at the time of this issue) were not covering this issue.

I'm still happy to accept PR's to address any outstanding issues.

Thanks
