### ISSUE TITLE
Gem in combination with rails 3.2.19 complains about uninitialized constant RAILS_CACHE

### ISSUE THREAD

**Issue by errier** [tra/spawnling#51]
Running rails console gives:

/var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails.rb:90:in `cache': uninitialized constant RAILS_CACHE (NameError)
    from /var/lib/gems/1.9.1/gems/spawnling-2.1.5/lib/patches.rb:138:in`<top (required)>'
    from /var/lib/gems/1.9.1/gems/spawnling-2.1.5/lib/spawnling.rb:250:in `require'
    from /var/lib/gems/1.9.1/gems/spawnling-2.1.5/lib/spawnling.rb:250:in`<top (required)>'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in`block (2 levels) in require'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in`block in require'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in`require'
    from /var/lib/gems/1.9.1/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /export/www/myapp/ruby/config/application.rb:13:in`<top (required)>'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/commands.rb:39:in `require'
    from /var/lib/gems/1.9.1/gems/railties-3.2.19/lib/rails/commands.rb:39:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

Temp solution for Rails 3 is to downgrade to rails 3.2.18 and spawnling 2.1.1

**Comment by felixbuenemann** [comment]
Try `gem 'spawnling', require: false`in Gemfile and manually `require 'spawnling'` after rails has been loaded, eg. from `config/intializers/spawnling.rb`.

**Comment by errier** [comment]
@felixbuenemann @mnoack There is a pull request since october 8 2014 that's using a Railtie to do this.

**Comment by mnoack** [comment]
Merged. I think it either broke the specs or because it lowered the coverage I didn't want to approve it at the time, but those really seem like petty issues at this stage so I've merged it.

**Comment by mnoack** [comment]
Closing this issue as it was addressed
