### ISSUE TITLE
Cannot use :method => :thread

### ISSUE THREAD

**Issue by fritzr** [tra/spawnling#54]
The README says use `:method => :thread`, but I have to use `:method => :threads` instead.

```ruby
irb(main):016:0> s= Spawnling.new(:method=>:thread) do puts 'hi' end
NoMethodError: undefined method `error' for nil:NilClass
	from (irb):16:in `new'
	from (irb):16
	from <root>/bin/rails:8:in `<top (required)>'
	from -e:1:in `<main>'
```
```ruby
irb(main):021:0> Spawnling.new(:method=>:threads) do puts 'hi' end
=> #<Spawnling:0x007f38f27348a8 @type=:fork, @handle=17866>
irb(main):022:0> hi
```

I'm in RoR:
```bash
[devpc ~]$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
[devpc ~]$ rails --version
Rails 4.2.4
```

**Comment by fritzr** [comment]
UPDATE: Actually, `:method => :threads` is NOT doing what I wanted. You can even see it in the message output I posted. Looks like Spawnling will take anything for `:method` and just default to `fork`.

```ruby
irb(main):034:0> s = Spawnling.new(:method => :bob) do end
=> #<Spawnling:0x007f6ca67953f0 @type=:fork, @handle=32433>
irb(main):035:0> s.type
=> :fork
```

Even still, `:method => :thread` doesn't work, and still gives the error I posted originally.

(By the way, didn't put this in the original post but I'm using `spawnling-2.1.6`.)

**Comment by fritzr** [comment]
Looks like it is because `@@logger` is not successfully initialized, and it's trying to dump the error  `spawn requires config.active_record.allow_concurrency=true`.

This must be an artifact of the `@@logger` initialization syntax with my version of Ruby (`2.2.3p173`). Fortunately I can get around it by setting the logger manually:

```ruby
irb(main):059:0> Spawnling.logger= Rails.logger
=> #<ActiveSupport::Logger:0x007f6ca6996c08 @progname=nil, @level=0, ...
irb(main):060:0> Spawnling.new(:method => :thread) do end
spawn(:method=>:thread) only allowed when allow_concurrency=true
RuntimeError: spawn requires config.active_record.allow_concurrency=true when used with :method=>:thread
	from (irb):60:in `new'
	from (irb):60
	from <root>/bin/rails:8:in `<top (required)>'
	from -e:1:in `<main>'
irb(main):061:0> 
```

Probably would be a good thing to fix...

**Comment by mnoack** [comment]
@fritzr I've resolved the fact that ':threads' becomes :fork in https://github.com/tra/spawnling/pull/55

So now any invalid values like :threads will give an error.

If you can make a pull request (with a test ideally) to resolve the issue I'll gladly review it.

**Comment by DennisWormald** [comment]
@fritzr thank you! I used your Spawnling.logger = Rails.logger to fix the same bug, my rails logs in heroku were also not showing any errors if they occured in the spawned fork, but with this change they do. In rails 5.0.7, ruby 2.3.4
