### ISSUE TITLE
Question: Timeframe for releasing current changes

### ISSUE THREAD

**Issue by harukizaemon** [tra/spawnling#56]
Hi,

Wondering if you had a schedule in mind for releasing master to RubyGems? I looked at the diffs and there's not much I would be worried about but I do like to keep up-to-date with critical infrastructure such as Spawling.

Thanks,

Simon

**Comment by mnoack** [comment]
@harukizaemon Master only has testing related fixes to keep it working with newer ruby versions/gems. It doesn't feel worthy of a release. Happy to release if there's sometime worthy of releasing.
